travel/travelrecomend/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

from travel import views
#用于前后端连接
urlpatterns = [
                  path("admin/", admin.site.urls),
                  path("", views.index, name="index"),
                  path("login/", views.login, name="login"),
                  path("register/", views.register, name="register"),
                  path("logout/", views.logout, name="logout"),
                  path("all_movie/", views.index, name="all_movie"),
                  path("travel/<int:movie_id>/", views.movie, name="travel"),
                  path("score/<int:movie_id>/", views.score, name="score"),
                  path("comment/<int:movie_id>/", views.make_comment, name="comment"),
                  path("like_comment/<int:comment_id>/<int:movie_id>/", views.like_comment, name="like_comment"),
                  path("unlike_comment/<int:comment_id>/<int:movie_id>/", views.unlike_comment, name="unlike_comment"),
                  path("collect/<int:movie_id>/", views.collect, name="collect"),
                  path("decollect/<int:movie_id>/", views.decollect, name="decollect"),
                  path("personal/", views.personal, name="personal"),
                  path("mycollect/", views.mycollect, name="mycollect"),
                  path("my_comments/", views.my_comments, name="my_comments"),
                  path("my_rate/", views.my_rate, name="my_rate"),
                  path("delete_comment/<int:comment_id>", views.delete_comment, name="delete_comment"),
                  path("delete_rate/<int:rate_id>", views.delete_rate, name="delete_rate"),
                  path("hot_movie/", views.hot_movie, name="hot_movie"), # 收藏最多
                  path("most_view/", views.most_view, name="most_view"),
                  path("most_mark/", views.most_mark, name="most_mark"),
                  path("latest_movie/", views.latest_movie, name="latest_movie"),
                  # path("mark_sort/", views.mark_sort, name="mark_sort"),
                  path("search/", views.search, name="search"),
                  path("all_tags/", views.all_tags, name="all_tags"),
                  path("one_tag/<int:one_tag_id>/", views.one_tag, name="one_tag"),
                  path("choose_tags/", views.choose_tags, name="choose_tags"),
                  path("director_movie/<str:director_name>", views.director_movie, name="director_movie"),
                  path("user_recommend/", views.user_recommend, name="user_recommend"),#用户推荐
                  path("item_recommend/", views.item_recommend, name="item_recommend"),#物品推荐
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

admin.site.site_header = '推荐系统后台管理'
admin.site.index_title = '首页-推荐系统'
admin.site.site_title = '推荐系统'

travel/travel/models.py
from datetime import datetime
from datetime import date
from django.db import models
from django.db.models import Avg
from django.db.models.fields.files import FileField
from itertools import chain
#数据库表
class User(models.Model):
    username = models.CharField(max_length=255, unique=True, verbose_name="账号")#unique唯一（不重复）
    password = models.CharField(max_length=255, verbose_name="密码")
    email = models.EmailField(verbose_name="邮箱")
    created_time = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = "用户"
        verbose_name = "用户"

    def __str__(self):
        return self.username


class Tags(models.Model):
    name = models.CharField(max_length=255, verbose_name="标签", unique=True)

    class Meta:
        verbose_name = "标签"
        verbose_name_plural = "标签"

    def __str__(self):
        return self.name


class UserTagPrefer(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, verbose_name="用户id",
    )
    tag = models.ForeignKey(Tags, on_delete=models.CASCADE, verbose_name='标签名')
    score = models.FloatField(default=0)

    class Meta:
        verbose_name = "用户偏好"
        verbose_name_plural = "偏好"

    def __str__(self):
        return self.user.username + str(self.score)


class Movie(models.Model):
    tags = models.ManyToManyField(Tags, verbose_name='标签', blank=True)#多对多关系
    collect = models.ManyToManyField(User, verbose_name="收藏者", blank=True)
    name = models.CharField(verbose_name="景点名称", max_length=255, unique=True)
    director = models.CharField(verbose_name="景点地址", max_length=255)
    country = models.CharField(verbose_name="国家", max_length=255)
    years = models.DateField(verbose_name='日期')
    leader = models.CharField(verbose_name="其他", max_length=1024)
    d_rate_nums = models.IntegerField(verbose_name="评价数")
    d_rate = models.CharField(verbose_name="评分", max_length=255)
    intro = models.TextField(verbose_name="描述")
    num = models.IntegerField(verbose_name="浏览量", default=0)
    origin_image_link = models.URLField(verbose_name='图片地址', max_length=255, null=True)
    image_link = models.FileField(verbose_name="封面图片", max_length=255, upload_to='movie_cover')
    imdb_link = models.URLField(null=True)

    @property
    def movie_rate(self):
        movie_rate = Rate.objects.filter(movie_id=self.id).aggregate(Avg('mark'))['mark__avg']
        return movie_rate or '无'

    class Meta:
        verbose_name = "景点"
        verbose_name_plural = "景点"

    def __str__(self):
        return self.name

    def to_dict(self, fields=None, exclude=None):
        opts = self._meta
        data = {}
        for f in chain(opts.concrete_fields, opts.private_fields, opts.many_to_many):
            if exclude and f.name in exclude:
                continue
            if fields and f.name not in fields:
                continue
            value = f.value_from_object(self)
            if isinstance(value, date):
                value = value.strftime('%Y-%m-%d')
            elif isinstance(f, FileField):
                value = value.url if value else None
            data[f.name] = value
        return data

#用户对电影打分数据
class Rate(models.Model):
    movie = models.ForeignKey(
        Movie, on_delete=models.CASCADE, blank=True, null=True, verbose_name="电影id"
    )
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, blank=True, null=True, verbose_name="用户id",
    )
    mark = models.FloatField(verbose_name="评分")
    create_time = models.DateTimeField(verbose_name="发布时间", auto_now_add=True)

    @property
    def avg_mark(self):
        average = Rate.objects.all().aggregate(Avg('mark'))['mark__avg']#求平均分
        return average

    class Meta:
        verbose_name = "评分信息"
        verbose_name_plural = verbose_name

#电影评论表
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="用户")#外建关联
    content = models.CharField(max_length=255, verbose_name="内容")
    create_time = models.DateTimeField(auto_now_add=True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE, verbose_name="电影")

    class Meta:
        verbose_name = "评论"
        verbose_name_plural = verbose_name


class LikeComment(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, verbose_name='评论')
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='用户')

    class Meta:
        verbose_name = "评论点赞"
        verbose_name_plural = verbose_name

travel/templates/all_tags.html
{% extends "base.html" %}
{% block main_content %}
    <div class="wrap-content">
        <div class="movie">
            <div class="row type">
                <div class="title">
                    <center><h2>旅游景点分类</h2></center>
                </div>
            </div>
            <div class="row">
                {% for tag in all_tags %}
                    <div class="col-1-4">
                        <div class="wrap-col">
                            <div class="post">
                                <div class="view effect">
                                    <div class="mask">
                                        <a href="{% url 'one_tag' tag.id %}" class="info"></a>
                                    </div>
                                </div>
                                <div class="clear"></div>
                                <a href="{% url 'one_tag' tag.id %}"><h3>{{ tag.name }}</h3></a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

travel/templates/base.html
{#{% load grav_tag %}#}
<!DOCTYPE html>
{% load static %}
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <title>推荐系统</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
    <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
    <link rel="stylesheet" href="{% static 'css/zerogrid.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN"
          crossorigin="anonymous">
</head>
<body>
<div class="wrap-body">
    <header>
        <div class="wrap-header zerogrid">
            <div class="row">
                <div class="col-1-2">
                    <div class="wrap-col">
                        <div class="logo" style="font-size: 33px;padding: 16px 0;font-family: sans-serif; ">
                            <a href="/"> 基于组合推荐算法旅游门户网站</a>
                        </div>
                    </div>
                </div>
                <div class="col-1-2">
                    <div class="wrap-col f-right">
                        <form method="post" action="{% url 'search' %}" id="search">
                            {% csrf_token %}
                            <input name="search" type="text" size="40" placeholder="搜索..."/>
                            <input type="submit" value="提交">
                        </form>
                    </div>
                </div>
            </div>
            <div class="row">
                <div id="menu">
                    <nav>
                        <div class="wrap-nav">
                            <ul>
                                <li class="active"><a href= {% url 'index' %}>首页</a></li>
                                <li class="active"><a href= {% url 'all_tags' %}>标签</a></li>
                                {% if request.session.login_in == True %}
                                    <li><a href="{% url 'personal' %}">{{ request.session.name }}</a></li>
                                    <li><a href="{% url 'logout' %}">退出登录</a></li>
                                {% else %}
                                    {{ request.session.login_in }}
                                    <li class="active"><a href= {% url 'login' %}>登录</a></li>
                                    <li class="active"><a href= {% url 'register' %}>注册</a></li>
                                       <li class="active"><a href= http://127.0.0.1:8000/admin>后台管理</a></li>
                                    {#                                    <li><a href="{% url 'clear_cache' %}">清除缓存</a></li>#}
                                {% endif %}
                            </ul>
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!--////////////////////////////////////Container-->
    <section id="container">
        <div class="wrap-container zerogrid">
            <div id="main-content" class="col-2-3">
                {% block main_content %}
                {% endblock %}
            </div>
            <div id="sidebar" class="col-1-3">
                <div class="wrap-sidebar">
                    <!---- Start Widget ---->
                    <div class="widget wid-new-updates">
                        <div class="wid-header">
                            <h5>最近更新</h5>
                        </div>
                        <div class="wid-content">
                            <ul id="latest-travel">
                                {% for movie in new_list %}
                                    <li><a href="{% url 'travel' movie.id %}">{{ movie.name }}</a><span><img src="/static/images/hot.png"/></span></li>
                                {% endfor %}
                            </ul>
                        </div>
                    </div>
                    <!---- Start Widget ---->
                    <div class="widget wid-last-updates">
                        <div class="wid-header">
                            <div class="row">
                                <div class="col-md-9">
                                    <h5> 基于用户推荐旅游景点</h5>
                                </div>
                                <div class="col-md-3">
                                    <a style="color: white" onclick="get_user_recommend()" href="#" class="btn btn-warning">换一批</a>
                                </div>
                            </div>
                        </div>
                        <div class="wid-content" id="user-recommend">
                            {% for movie in user_recommend_list %}
                                <div class="post">
                                    <a href="{% url 'travel' movie.id %}"><img src="{{ MEDIA_URL }}{{ movie.image_link }}"/></a>
                                    <div class="wrapper">
                                        <a href="{% url 'travel' movie.id %}"><h6>{{ movie.name }}</h6></a>
                                        <p>{{ movie.years }}</p>
                                        <a href="{% url 'travel' movie.id %}">评分{{ movie.rate }}</a>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--////////////////////////////////////Footer-->
    <footer>
        <div class="bottom-footer">
            <div class="wrap-bottom ">
                <div class="copyright">
{#                    <p>©2020 <a href="http://www.colaplusice.com/" target="_blank">Colaplusice</a>电影推荐系统</p>#}
                </div>
            </div>
        </div>
    </footer>


</div>
<script src="{% static 'js/jquery-2.1.1.min.js' %}"></script>
<script src="{% static "/js/bootstrap.min.js" %}"></script>
{#<script src="{% static 'js/css3-mediaqueries.js' %}"></script>#}
{% block bottom-js %}
{% endblock %}
<script>
    function get_user_recommend() {
        $.ajax({
            url: '/user_recommend/',
            type: 'GET',
            success: function (result) {
                var html = "";
                var array_length = result.length;
                for (var i = 0; i < array_length; i++) {
                    html += `<div class="post">\n` +
                        `<a href="/travel/${result[i].id}"><img src="${result[i].image_link}"/></a>` +
                        `<div class="wrapper"><a href="/travel/${result[i].id}"><h6>${result[i].name}</h6></a>`
                        + `<p> ${result[i].years}</p>`
                        + `<a href="/travel/${result[i].id}">评分${result[i].d_rate}</a>\n</div>`
                    ;
                }
                $('#user-recommend').html(html);
                {#console.log(html);#}
            },
            fail: function (xhr, textStatus, errorThrown) {
                alert('request failed');
            },
            error: function (jqXHR, exception) {
                console.log(jqXHR.status);
                console.log(exception);
            }
        });
    }

    get_user_recommend();

    function get_latest_movie() {
        $.ajax({
            url: '/latest_movie/',
            type: 'GET',
            success: function (result) {
                var html = "";
                var array_length = result.length;
                for (var i = 0; i < array_length; i++) {
                    html += `<li><a href="/travel/${result[i].id}">${result[i].name}</a><span><img src="/static/images/hot.png"/></span></li>`;
                }
                $('#latest-travel').html(html);
            },
            fail: function (xhr, textStatus, errorThrown) {
                alert('request failed');
            },
            error: function (jqXHR, exception) {
                console.log(jqXHR.status);
                console.log(exception);
            }
        });
    }

    get_latest_movie();

</script>

</body>
</html>

travel/templates/base_show.html
{% extends 'base.html' %}
{% block main_content %}
    <table class="table">
        <thead>
        <tr>
            {% block th_name %}
            {% endblock %}
        </tr>
        </thead>
        <tbody>
        {% for i in item %}
            <div class="modal" id="confirm-modal">
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-footer">
                        <div class="row">
                            <div class="col-md-6">
                                                           <button type="button" class="btn btn-block btn-default" data-dismiss="modal">不确认</button>
                            </div>
                            <div class="col-md-6">
                                   {% block modal %}
                            {% endblock %}
                            </div>
                        </div>

                        </div>
                    </div>
{#                </div>#}
            </div>
            <tr>
                {% block th_value %}
                {% endblock %}
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <!-- Button trigger modal -->
    <!-- Modal -->
{% endblock %}

travel/templates/choose_tag.html
{% extends 'base.html' %}
{% block main_content %}
    <h2 align="center"> 选择你喜欢的标签</h2>
    <div class="row">
        {% for tag in tags %}
            <div class="col-md-2">
                <label class="tags-input h2"><span class="label label-warning">{{ tag.name }}</span> </label>
            </div>
        {% endfor %}
    </div>
    <div class="row">
        <div class="col-md-4 col-md-offset-3" style="margin-top: 100px">
            <button class="btn btn-block btn-success" style="color: white"> 提交</button>
        </div>
    </div>
{% endblock %}

{% block bottom-js %}
    <script>
        var items = [];
        $("label").each(function (index) {
            let toggle = false;
            $(this).on("click", function () {
                console.log(toggle);
                toggle = !toggle;
                if (toggle === true) {
                    items.push($(this).text());
                    $(this).children('span').addClass('label-danger');

                } else
                //删除元素
                {
                    console.log("false");
                    items.splice(items.indexOf($(this).text()), 1);
                    $(this).children('span').removeClass('label-danger');
                }
                console.log(items);
            });
        });
        $('button').click(function () {
            $.ajax({
                url: '/choose_tags/',
                type: 'POST',
                contentType: 'application/json; charset=utf-8',
                data: JSON.stringify(items),
                {#返回的数据类型#}
                dataType: 'html',
                success: function (result) {
                    alert("选择成功!");
                    var newDoc = document.open("text/html", "replace");
                    newDoc.write(result);
                    newDoc.close();
                    {#$(html).html(result);#}
                },
                fail: function (xhr, textStatus, errorThrown) {
                    alert('request failed');
                },
                error: function (jqXHR, exception) {
                    console.log(jqXHR.status);
                    console.log(exception);
                }
            });
        })
    </script>

{% endblock %}

travel/templates/movie.html
{% extends "base.html" %}
{% load grav_tag %}
{% load is_like %}
{% block main_content %}
    <div class="wrap-content">
        <article>
            <div class="art-header">
                <div class="row">
                    <div class="col-md-3 " style="margin-bottom: 10px ;margin-top: 10px">
                        <img src="{{ MEDIA_URL }}{{ movie.image_link }}"/>
                    </div>
                    <div class="col-md-9">
                        <div class="wrap-col" style="overflow: auto">
                            <ul class="movie-info" style="overflow: auto">
                                <div class="row">
                                    <div class="col-md-6">
                                        <p>景点名字: <a href="#">{{ movie.name }}</a></p>
                                    </div>
                                    <div class="col-md-6">
                                        <p>日期: <a href="#">{{ movie.years }}</a></p>
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-md-6">
                                        <p>地址: <a href="#">{{ movie.director }}</a></p>
                                    </div>
                                    <div class="col-md-6">
                                        <p>其他: <a href="#">{{ movie.leader |slice:30 }}...</a></p>
                                    </div>
                                </div>
                                <li>
                                    <div class="row">
                                        <div class="col-1-3">
                                            <a target="_blank" style="display: inline-block; margin-left: 15px" class="btn-lg btn-success" href="https://piao.qunar.com/ticket/list.htm?keyword={{ movie.name }}">购买景点门票</a>
                                        </div>
                                        <div class="col-1-3">
                                            {% if is_collect %}
                                                <a class="btn-lg btn-warning" style="display: inline-block" href="{% url 'decollect' movie.id %}">取消收藏</a>
                                            {% else %}
                                                <a class="btn-lg btn-primary" style="display: inline-block" href="{% url 'collect' movie.id %}">点击收藏</a>{% endif %}
                                        </div>
                                        <div class="col-1-3">
                                            <h2 style="display: inline"> 收藏人数:{{ movie.collect.count }} </h2>
                                        </div>
                                        {#                                            <a style="display: inline-block" class="btn-lg btn-primary" href="{% url 'collect' travel.id %}">收藏</a>#}
                                    </div>
                                <li>
                                </li>
                                <li style="margin-top: 20px"><p style="display: inline-block; margin-right: 15px">景点评分: <a href="#">{{ movie.d_rate }}</a></p>
                                    <p style="display: inline-block">标签： {% for tag in movie.tags.all %}  <a href="{% url 'one_tag' tag.id %}">{{ tag.name }}</a>{% endfor %}</p>
                                </li>
                                <li style="margin-top: 20px">
                                    {% if user_rate is not None %}
                                        <h4>您已经进行打分: {{ user_rate.mark }}</h4>
                                    {% else %}
                                        <form action="{% url 'score' movie.id %}" method="post">
                                            {% csrf_token %}
                                            <p style="display: inline-block;"> 添加评分</p>
                                            <select name="score">
                                                <option>1.0</option>
                                                <option>2.0</option>
                                                <option>3.0</option>
                                                <option>4.0</option>
                                                <option>5.0</option>
                                            </select>
                                            <button type="submit" class="button bt1">提交</button>
                                        </form>
                                    {% endif %}
                                </li>
                                                            <div class="clear"></div>

                            </ul>
                        </div>
                    </div>
                </div>
            </div>
                        <div class="clear"></div>
            <div class="art-content">
                                <div class="clear"></div>
                <p>{{ movie.intro }}</p>
                <div class="clear"></div>
            </div>
        </article>
        <div class="widget wid-related">
            <div class="wid-header">
                <div class="row">
                    <div class="col-md-9">
                        <h5>基于物品算法推荐旅游景点</h5>
                    </div>
                    <div class="col-md-3">
                        <button class="button bt1" onclick="get_item_recommend()">换一批</button>
                    </div>
                </div>
            </div>
            <div class="wid-content">
                <div class="row" id="item-recommend">
                </div>
            </div>
        </div>
    </div>
    <div class="row clearfix">
        <div class="row">
            <div class="col-md-9">
                <form role="form" action="{% url 'comment' movie.id %}" method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <input placeholder="快来说说点什么吧" class="form-control" name="comment" cols="10" rows="10">
                    </div>
                    <div class="form-group">
                        <button type="submit" style="float: right;" class="btn-lg btn-success">提交评论</button>
                    </div>
                </form>
            </div>
            <div class="row">
                <div class="col-md-9">
                    <h2 style="border-bottom: dashed #fcab2b 1px; padding-bottom: 10px">评论</h2>
                    <div class="item-list">
                        <ul>
                            {% for i in comments %}
                                <li class="list-item">
                                    <div class="avartar">
                                        <a><img src='{{ request.user.email|gravatar:"75" }}'> </a>
                                    </div>
                                    <div class="list-info">
                                        <p>{{ i.content }}</p>
                                        {{ i.user.username }} 发表于{{ i.create_time }} 推荐
                                    </div>
                                    {#                                    {% if  i.user | is_like:i.user.id %}#}
                                    {#                                        <a href="{% url 'unlike_comment' i.id travel.id %}" class="recommend-link"><span class="fa fa-lg fa-thumbs-up"#}
                                    {#                                    {% else %}#}
                                    <a href="{% url 'like_comment' i.id movie.id %}" class="recommend-link"><span class="fa fa-lg fa-thumbs-up">({{ i.likecomment_set.count }})</span></a>
                                    {#                                    {% endif %}#}
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

{% block bottom-js %}
    <script>
        function get_item_recommend() {
            $.ajax({
                url: '/item_recommend/',
                type: 'GET',
                success: function (result) {
                    var html = "";
                    var array_length = result.length;
                    for (var i = 0; i < array_length; i++) {
                        html += `<div class="col-1-3"><div class="wrap-col">` +
                            `<a href="/travel/${result[i].id}"><img src="${result[i].image_link}"/></a>` +
                            `<a href="/travel/${result[i].id}"><h4>${result[i].name}</h4></a></div></div>`;
                    }
                    $('#item-recommend').html(html);
                },
                fail: function (xhr, textStatus, errorThrown) {
                    alert('request failed');
                },
                error: function (jqXHR, exception) {
                    console.log(jqXHR.status);
                    console.log(exception);
                }
            });
        }

        get_item_recommend();
    </script>


{% endblock %}

travel/templates/my_comment.html
{% extends "base_show.html" %}
{% block th_name %}
    <th>景点</th>
    <th>评论内容</th>
    <th>评论时间</th>
    <th>删除</th>
{% endblock %}
{% block modal %}
    <a class="btn btn-primary btn-block" href="{% url 'delete_comment' i.id %}">确认</a>

{% endblock %}
{% block th_value %}
    <td>{{ i.movie.name }}</td>
    <td>{{ i.content }}</td>
    <td>{{ i.create_time }}</td>
    <td><a class="btn btn-danger" data-toggle="modal" data-target="#confirm-modal">删除</a></td>
{% endblock %}

travel/templates/my_rate.html
{% extends "base_show.html" %}
{% block th_name %}
    <th>景点</th>
    <th>评分</th>
    <th>时间</th>
    <th>编辑</th>
{% endblock %}
{% block modal %}
    <a class="btn btn-primary btn-block" href="{% url 'delete_rate' i.id %}">确认</a>
{% endblock %}
{% block th_value %}
    <td><a href="{% url 'travel' i.movie.id %}"> {{ i.movie.name }}</a></td>
    <td>{{ i.mark }}</td>
    <td>{{ i.create_time }}</td>
    <td><a class="btn btn-danger" data-toggle="modal" data-target="#confirm-modal">删除</a></td>
{% endblock %}

travel/templates/mycollect.html
{% extends "base_show.html" %}
{% block th_name %}
    <th>景点</th>
    <th>地址</th>
    <th>标签</th>
    <th>查看</th>
{% endblock %}
{% block th_value %}
    <td><a href="{% url 'travel' i.id %}"> {{ i.name }}</a></td>
    <td><a href="{% url 'director_movie' i.director %}">{{ i.director }}</a></td>
    <td> {% if i.tags.all %}
        {% for tag in i.tags.all %}
            <a href="{% url 'one_tag' tag.id %}">{{ tag }}</a>
        {% endfor %}
    {% else %}
        无
    {% endif %}
    </td>
    <td><a class="btn btn-success" href="{% url 'travel' i.id %}">查看</a></td>
{% endblock %}